FROM node:17-alpine 

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY ./package.json /app/package.json

COPY ./package-lock.json /app/package-lock.json

RUN npm install

COPY ./ /app

RUN npx prisma generate

RUN sh -c "sleep 5"

CMD sh -c  "npx prisma db push && npm run watch:debug"
