version: "3"

services:
    nft-service:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        image: nft-service
        container_name: nft-service
        environment: 
            TITLE: nft-service
            NODE_ENV: development
            MONGO_DEV_USER: ${MONGO_DEV_USER}
            MONGO_DEV_PASSWORD: ${MONGO_DEV_PASSWORD}
            MONGO_DATABASE: test-database            
            MONGO_DATABASE_URL: 'mongodb://mongodb1:27017/test-database'            
            ALLOWED_ORIGINS: '["*"]'
            DEBUG: "*"
            PORT: 8080
        depends_on:
            - mongodb1          
        volumes:
            - ./prisma:/app/prisma
            - ./src:/app/src
            - ./models:/app/models
            - nft-service-node_modules:/app/node_modules
            - ./node_modules/.prisma:/app/node_modules/.prisma
            - ./data:/app/data
        restart: 'always'
        ports:
            - 8080:8080
            - 9229:9229

    mongodb1:
        image: mongo:4
        restart: always
        container_name: mongodb1
        environment:
            - MONGO_INITDB_DATABASE=test-database
        volumes:
        - mongodata1:/data/db
        expose:
        - "27017"
        ports:
        - 27017:27017 #Only in dev open ports to the outside!        
        entrypoint: [ "/usr/bin/mongod", "--replSet", "${MONGO_REPLICA_SET_NAME}", "--bind_ip_all", "--wiredTigerCacheSizeGB", "1"]

    mongodb2:
        image: mongo:4
        restart: always
        container_name: mongodb2
        environment:
            - MONGO_INITDB_DATABASE=test-database     
        volumes:
        - mongodata2:/data/db
        expose:
        - "27017"
        entrypoint: [ "/usr/bin/mongod", "--replSet", "${MONGO_REPLICA_SET_NAME}", "--bind_ip_all", "--wiredTigerCacheSizeGB", "1"]

    mongosetup:
        image: "mongo-setup"
        build: "./mongo-setup"
        container_name: "mongosetup"
        depends_on:
            - mongodb1
        volumes:
            - mongostatus:/data/           

volumes: 
    nft-service-node_modules:
    mongodata1:
    mongodata2:
    mongostatus:
